[package]
name = "Guessing-Game"
version = "0.1.0"
authors = ["Daniel Kogan <54873722+daminals@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"